<?php

namespace Database\Seeders;

use App\Models\Agent;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AgentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $agents = [
            // KG & R Locations - sort_order 1-5
            ['name' => 'KG & R - Beitbridge (BBR)', 'type' => 'both', 'location' => 'BBR', 'sort_order' => 1],
            ['name' => 'KG & R - Groblersbrug (GRB)', 'type' => 'both', 'location' => 'GRB', 'sort_order' => 2],
            ['name' => 'KG & R - Kopfontein (KOP)', 'type' => 'both', 'location' => 'KOP', 'sort_order' => 3],
            ['name' => 'KG & R - Skilpadshek (SKH)', 'type' => 'both', 'location' => 'SKH', 'sort_order' => 4],
            ['name' => 'KG & R - Tlokweng', 'type' => 'both', 'location' => 'Tlokweng', 'sort_order' => 5],

            // Major Clearing Agents - sort_order 10+
            ['name' => 'Aero Africa', 'type' => 'both', 'sort_order' => 10],
            ['name' => 'Afnet', 'type' => 'both', 'sort_order' => 11],
            ['name' => 'Africlearing', 'type' => 'both', 'sort_order' => 12],
            ['name' => 'AGL', 'type' => 'both', 'sort_order' => 13],
            ['name' => 'Air Menzies', 'type' => 'both', 'sort_order' => 14],
            ['name' => 'AMI', 'type' => 'both', 'sort_order' => 15],
            ['name' => 'BIL', 'type' => 'both', 'sort_order' => 16],
            ['name' => 'Botcon', 'type' => 'both', 'sort_order' => 17],
            ['name' => 'Builtline Cargo', 'type' => 'both', 'sort_order' => 18],
            ['name' => 'Cargo Compass', 'type' => 'both', 'sort_order' => 19],
            ['name' => 'Cargo Services', 'type' => 'both', 'sort_order' => 20],
            ['name' => 'CF Global Logistics', 'type' => 'both', 'sort_order' => 21],
            ['name' => 'CML', 'type' => 'both', 'sort_order' => 22],
            ['name' => 'CML & H&D', 'type' => 'both', 'sort_order' => 23],
            ['name' => 'Comexas', 'type' => 'both', 'sort_order' => 24],
            ['name' => 'Connex', 'type' => 'both', 'sort_order' => 25],
            ['name' => 'Container Purchase', 'type' => 'both', 'sort_order' => 26],
            ['name' => 'Coretrust', 'type' => 'both', 'sort_order' => 27],
            ['name' => 'Corsair', 'type' => 'both', 'sort_order' => 28],
            ['name' => 'Darrant', 'type' => 'both', 'sort_order' => 29],
            ['name' => 'Desert Charm', 'type' => 'both', 'sort_order' => 30],
            ['name' => 'Dontong', 'type' => 'both', 'sort_order' => 31],
            ['name' => 'Dynalog', 'type' => 'both', 'sort_order' => 32],
            ['name' => 'Epsylog', 'type' => 'both', 'sort_order' => 33],
            ['name' => 'Esse Clearing', 'type' => 'both', 'sort_order' => 34],
            ['name' => 'Greendoor Group', 'type' => 'both', 'sort_order' => 35],
            ['name' => 'H&D (Z) LTD', 'type' => 'both', 'sort_order' => 36],
            ['name' => 'H&D / Tradelog', 'type' => 'both', 'sort_order' => 37],
            ['name' => 'Hello Logistic', 'type' => 'both', 'sort_order' => 38],
            ['name' => 'Jeromenono Invest', 'type' => 'both', 'sort_order' => 39],
            ['name' => 'Leman Finland', 'type' => 'both', 'sort_order' => 40],
            ['name' => 'Link Express', 'type' => 'both', 'sort_order' => 41],
            ['name' => 'LV Logistics', 'type' => 'both', 'sort_order' => 42],
            ['name' => 'Malabar', 'type' => 'both', 'sort_order' => 43],
            ['name' => 'Manuport Logistics', 'type' => 'both', 'sort_order' => 44],
            ['name' => 'Mark Shipping', 'type' => 'both', 'sort_order' => 45],
            ['name' => 'MKFS', 'type' => 'both', 'sort_order' => 46],
            ['name' => 'Namgola', 'type' => 'both', 'sort_order' => 47],
            ['name' => 'Nucleus', 'type' => 'both', 'sort_order' => 48],
            ['name' => 'OMA Shipping and Logistics', 'type' => 'both', 'sort_order' => 49],
            ['name' => 'Peg Transport', 'type' => 'both', 'sort_order' => 50],
            ['name' => 'Polytra', 'type' => 'both', 'sort_order' => 51],
            ['name' => 'Poseidon Freight', 'type' => 'both', 'sort_order' => 52],
            ['name' => 'RDM', 'type' => 'both', 'sort_order' => 53],
            ['name' => 'Remant Logistics', 'type' => 'both', 'sort_order' => 54],
            ['name' => 'RG & B', 'type' => 'both', 'sort_order' => 55],
            ['name' => 'Rhenues', 'type' => 'both', 'sort_order' => 56],
            ['name' => 'Safpack', 'type' => 'both', 'sort_order' => 57],
            ['name' => 'Sediba', 'type' => 'both', 'sort_order' => 58],
            ['name' => 'Simba Supply Chain Solutions', 'type' => 'both', 'sort_order' => 59],
            ['name' => 'Supergroup', 'type' => 'both', 'sort_order' => 60],
            ['name' => 'Swift Clearing', 'type' => 'both', 'sort_order' => 61],
            ['name' => 'Tradelog', 'type' => 'both', 'sort_order' => 62],
            ['name' => 'Tradelog / Tran Solution', 'type' => 'both', 'sort_order' => 63],
            ['name' => 'Transfreight', 'type' => 'both', 'sort_order' => 64],
            ['name' => 'U.B. Freight Limited', 'type' => 'both', 'sort_order' => 65],
            ['name' => 'Visimanyikwa General', 'type' => 'both', 'sort_order' => 66],
            ['name' => 'Western Logistics', 'type' => 'both', 'sort_order' => 67],

            // Additional Entry Agents - Alphabetically sorted, sort_order 200+
            ['name' => 'A&C LDA', 'type' => 'entry', 'sort_order' => 200],
            ['name' => 'A&C LDA Despachantes Aduaneiros Associados', 'type' => 'entry', 'sort_order' => 201],
            ['name' => 'AGL (African Global Logistics)', 'type' => 'entry', 'sort_order' => 202],
            ['name' => 'AGL - Kasumbalesa', 'type' => 'entry', 'location' => 'Kasumbalesa', 'sort_order' => 203],
            ['name' => 'African Global Logistics', 'type' => 'entry', 'sort_order' => 204],
            ['name' => 'African Skies', 'type' => 'entry', 'sort_order' => 205],
            ['name' => 'AGK', 'type' => 'entry', 'sort_order' => 206],
            ['name' => 'AGSIM', 'type' => 'entry', 'sort_order' => 207],
            ['name' => 'AWA Logistics', 'type' => 'entry', 'sort_order' => 208],
            ['name' => 'Benka Logistics', 'type' => 'entry', 'sort_order' => 209],
            ['name' => 'BS Company SARL', 'type' => 'entry', 'sort_order' => 211],
            ['name' => 'Cargo Congo', 'type' => 'entry', 'sort_order' => 212],
            ['name' => 'CEVA Logistics', 'type' => 'entry', 'sort_order' => 214],
            ['name' => 'Chemaf', 'type' => 'entry', 'sort_order' => 215],
            ['name' => 'Client', 'type' => 'entry', 'sort_order' => 216],
            ['name' => 'Connex Africa', 'type' => 'entry', 'sort_order' => 219],
            ['name' => 'Customs Services', 'type' => 'entry', 'sort_order' => 222],
            ['name' => 'Danny', 'type' => 'entry', 'sort_order' => 223],
            ['name' => 'DHL Global Forwarding', 'type' => 'entry', 'sort_order' => 225],
            ['name' => 'DHL Global Forwarding - Mozambique', 'type' => 'entry', 'sort_order' => 226],
            ['name' => 'DLS-SL', 'type' => 'entry', 'sort_order' => 227],
            ['name' => 'Douane Express', 'type' => 'entry', 'sort_order' => 228],
            ['name' => 'Douane Express Customs', 'type' => 'entry', 'sort_order' => 229],
            ['name' => 'EG Mining', 'type' => 'entry', 'sort_order' => 232],
            ['name' => 'Epsylog China', 'type' => 'entry', 'sort_order' => 233],
            ['name' => 'EST - Despacho Aduaneiro', 'type' => 'entry', 'sort_order' => 234],
            ['name' => 'FBM-Lubumbashi International Airport', 'type' => 'entry', 'location' => 'Lubumbashi', 'sort_order' => 235],
            ['name' => 'FedEx', 'type' => 'entry', 'sort_order' => 236],
            ['name' => 'Freight Forwarders Tanzania Limited', 'type' => 'entry', 'sort_order' => 237],
            ['name' => 'GARP', 'type' => 'entry', 'sort_order' => 238],
            ['name' => 'GARP-Nacala', 'type' => 'entry', 'location' => 'Nacala', 'sort_order' => 239],
            ['name' => 'Gecotrans', 'type' => 'entry', 'sort_order' => 240],
            ['name' => 'GLS', 'type' => 'entry', 'sort_order' => 241],
            ['name' => 'Hamla General Dealers', 'type' => 'entry', 'sort_order' => 242],
            ['name' => 'Hand Carry Shipment', 'type' => 'entry', 'sort_order' => 243],
            ['name' => 'Hill & Delamain (H&D)', 'type' => 'entry', 'sort_order' => 244],
            ['name' => 'Hill & Delamain (Z) LTD', 'type' => 'entry', 'sort_order' => 245],
            ['name' => 'Hill And Delamain', 'type' => 'entry', 'sort_order' => 246],
            ['name' => 'Inertia', 'type' => 'entry', 'sort_order' => 247],
            ['name' => 'Iscotrans', 'type' => 'entry', 'sort_order' => 248],
            ['name' => 'JNB-O.R. Tambo International Airport', 'type' => 'entry', 'location' => 'Johannesburg', 'sort_order' => 249],
            ['name' => 'Kasumbalesa', 'type' => 'entry', 'location' => 'Kasumbalesa', 'sort_order' => 250],
            ['name' => 'Kentanuga', 'type' => 'entry', 'sort_order' => 251],
            ['name' => 'KG & R - GRB', 'type' => 'entry', 'location' => 'GRB', 'sort_order' => 252],
            ['name' => 'KG&R Agencies', 'type' => 'entry', 'sort_order' => 253],
            ['name' => 'Kipushi', 'type' => 'entry', 'location' => 'Kipushi', 'sort_order' => 254],
            ['name' => 'Kudumu Logistics', 'type' => 'entry', 'sort_order' => 255],
            ['name' => 'LBH', 'type' => 'entry', 'sort_order' => 256],
            ['name' => 'LBH Pemba', 'type' => 'entry', 'location' => 'Pemba', 'sort_order' => 257],
            ['name' => 'Legendre', 'type' => 'entry', 'sort_order' => 258],
            ['name' => 'Lubumbashi', 'type' => 'entry', 'location' => 'Lubumbashi', 'sort_order' => 259],
            ['name' => 'Malabar Clearing', 'type' => 'entry', 'sort_order' => 261],
            ['name' => 'Maun', 'type' => 'entry', 'location' => 'Maun', 'sort_order' => 262],
            ['name' => 'Mike Ngoie', 'type' => 'entry', 'sort_order' => 263],
            ['name' => 'Moatize', 'type' => 'entry', 'location' => 'Moatize', 'sort_order' => 264],
            ['name' => 'Moma', 'type' => 'entry', 'location' => 'Moma', 'sort_order' => 265],
            ['name' => 'Nacala', 'type' => 'entry', 'location' => 'Nacala', 'sort_order' => 266],
            ['name' => 'OBT Shipping', 'type' => 'entry', 'sort_order' => 267],
            ['name' => 'Paul Express', 'type' => 'entry', 'sort_order' => 268],
            ['name' => 'Pemba', 'type' => 'entry', 'location' => 'Pemba', 'sort_order' => 269],
            ['name' => 'Red Rock Mineral Resource Africa', 'type' => 'entry', 'sort_order' => 271],
            ['name' => 'Rio Tinto Simfer S.A.', 'type' => 'entry', 'sort_order' => 272],
            ['name' => 'SACO', 'type' => 'entry', 'sort_order' => 273],
            ['name' => 'Sociedade de Despachos LDA', 'type' => 'entry', 'sort_order' => 275],
            ['name' => 'Sogecodel', 'type' => 'entry', 'sort_order' => 276],
            ['name' => 'Spedag', 'type' => 'entry', 'sort_order' => 277],
            ['name' => 'Swift Global Service', 'type' => 'entry', 'sort_order' => 279],
            ['name' => 'TBA', 'type' => 'entry', 'sort_order' => 280],
            ['name' => 'Trade Service', 'type' => 'entry', 'sort_order' => 281],
            ['name' => 'Trade Services', 'type' => 'entry', 'sort_order' => 282],
            ['name' => 'Tradex Consulting', 'type' => 'entry', 'sort_order' => 284],
            ['name' => 'Tritone Express', 'type' => 'entry', 'sort_order' => 285],
            ['name' => 'Union Logistics', 'type' => 'entry', 'sort_order' => 286],
            ['name' => 'Whright Line', 'type' => 'entry', 'sort_order' => 288],
            ['name' => 'Wolfways', 'type' => 'entry', 'sort_order' => 289],
            ['name' => 'Wright Line', 'type' => 'entry', 'sort_order' => 290],

            // Special Cases - sort_order 900+
            ['name' => 'Not Applicable', 'type' => 'both', 'sort_order' => 900],
            ['name' => 'Not Applicable - Local Transport', 'type' => 'both', 'sort_order' => 901],
            ['name' => 'N/A', 'type' => 'both', 'sort_order' => 902],
        ];

        foreach ($agents as $agent) {
            Agent::create($agent);
        }
    }
}
